In [1]:
import numpy as np 
import pandas as pd

In [6]:
dataset = pd.read_csv("Data.csv")

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Country                  660 non-null    object
 1   League                   660 non-null    object
 2   Club                     626 non-null    object
 3   Player Names             660 non-null    object
 4   Matches_Played           660 non-null    int64
 5   Substitution             660 non-null    int64
 6   Mins                     660 non-null    int64
 7   Goals                    660 non-null    int64
 8   xG                       660 non-null    float64
 9   xG Per Avg Match         660 non-null    float64
 10  Shots                    660 non-null    int64
 11  OnTarget                 660 non-null    int64
 12  Shots Per Avg Match      660 non-null    float64
 13  On Target Per Avg Match  660 non-null    float64
 14  Year                     660 non-null    int64
dtypes: float64(4), int64(7), object(4)
memory usage: 77.5+ KB

In [8]:
dataset.head()

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016

In [9]:
df =  pd.DataFrame(dataset)

In [10]:
df.describe()

,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
count,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000,660.000000
mean,22.371212,3.224242,2071.416667,11.784848,10.089606,0.476167,64.177273,28.365152,2.948015,1.315652,2018.363636
std,9.754658,3.839498,900.595049,5.982454,5.724844,0.192831,34.941622,16.363149,0.914906,0.474239,1.367700
min,2.000000,0.000000,264.000000,2.000000,0.710000,0.070000,5.000000,2.000000,0.800000,0.240000,2016.000000
25%,14.000000,0.000000,1363.500000,8.000000,6.100000,0.340000,37.750000,17.000000,2.335000,0.980000,2017.000000
50%,24.000000,2.000000,2245.500000,11.000000,9.285000,0.435000,62.000000,26.000000,2.845000,1.250000,2019.000000
75%,31.000000,5.000000,2822.000000,14.000000,13.252500,0.570000,86.000000,37.000000,3.382500,1.540000,2019.000000
max,38.000000,26.000000,4177.000000,37.000000,32.540000,1.350000,208.000000,102.000000,7.200000,3.630000,2020.000000

L'equipe qui fait plus de tirs tout championnat comfondu

In [18]:
shots = dataset.groupby('League')[['Club','Shots']].sum()

shots

,Club,Shots
League,,
Bundesliga,(HKI)(BMG)(BAY)Sandro(HOF)(FCA)(BAY)(RBL)(CHE)...,6039
Campeonato Brasileiro SÃ©rie A,(GRE)(SAP)(MNC)(CEA)(SAP)(SAN)(HUR)(BOT)(FLA)(...,6197
Eredivisie,(AJA)(AJA)(AJA)(VIT)(FEY)(EMM)(VIT)(TWE)(SPR)(...,1632
France Ligue 1,(PSG)(PSG)(PSG),245
France Ligue 10,(STE)(STE)(MON),184
France Ligue 11,(PSG)(REN)(LYO),193
France Ligue 12,(CAE)(MPE)(ANG),150
France Ligue 13,(MPE)(MAR)(NIC),175
France Ligue 14,(SIV)(LEI)(MAR),194
France Ligue 15,(REN)(LYO)(LEN),126
France Ligue 16,(ANG)(REN)(LIL),136
France Ligue 17,(LOK)(REN)(STR),127
France Ligue 18,(STR)(PSG)(NAN),129
France Ligue 19,(LYO)(STR)(DIJ),190
France Ligue 2,(ARS)(MON)(REI),207
France Ligue 20,(BOR)(STR)(PSG),142
France Ligue 3,(MNU)(LYO)(MPE),139
France Ligue 4,(MAR)(NAP)(LIL),215
France Ligue 5,(LYO)(STR)(MET),194
France Ligue 6,(PSG)(PSG)(MON),120
France Ligue 7,(GAL)(PSG)(LEN),183
France Ligue 8,(MPE)(MAR)(BRE),201
France Ligue 9,(LIL)(NIC)(LYO),136
La Liga,(BET)(BAR)(ATL)(CAR)(VAL)(JUV)(RMA)(PSG)(CEL)(...,6913
MLS,(LAF)(ATA)(ACM)(SJE)(ORL)(PHI)(MIN)(CHF)(CCR)(...,2697
Premier League,(INT)(INT)(TOT)(LEI)(CRY)(ROM)(RMA)(LIV)(LIV)(...,5770
Primeira Liga,(LIS)(FAR)(BRA)(BRA)(AVE)(FAM)(FAM)(POR)(BEN)(...,1510
Serie A,(LIV)(SAS)(LAZ)(VER)(NAP)(ATA)(FIO)(BEN)(CAG)(...,8213